# 02-access-services.sh
#!/bin/bash

echo "========================================="
echo " Доступ к сервисам Microservices Demo"
echo "========================================="

echo ""
echo "1. Minikube dashboard:"
echo "   minikube dashboard"
echo ""

echo "2. Проксирование сервисов:"
echo ""
echo "   Prometheus (метрики):"
echo "   kubectl port-forward svc/prometheus 9090:9090 -n microservices-demo"
echo "   Затем откройте: http://localhost:9090"
echo ""
echo "   Grafana (дашборды):"
echo "   kubectl port-forward svc/grafana 3000:3000 -n microservices-demo"
echo "   Затем откройте: http://localhost:3000"
echo "   Логин: admin"
echo "   Пароль: admin123"
echo ""
echo "   User Service API:"
echo "   kubectl port-forward svc/user-service 8080:8000 -n microservices-demo"
echo "   Затем тестируйте:"
echo "   curl http://localhost:8080/health"
echo "   curl http://localhost:8080/users"
echo "   curl http://localhost:8080/metrics"
echo ""

echo "3. Прямой доступ через NodePort:"
echo ""
PROM_PORT=$(kubectl get svc prometheus -n microservices-demo -o jsonpath='{.spec.ports[0].nodePort}')
GRAFANA_PORT=$(kubectl get svc grafana -n microservices-demo -o jsonpath='{.spec.ports[0].nodePort}')
echo "   Prometheus: http://$(minikube ip):$PROM_PORT"
echo "   Grafana:    http://$(minikube ip):$GRAFANA_PORT"
echo ""

echo "4. Полезные команды:"
echo "   Просмотр логов User Service:"
echo "   kubectl logs deployment/user-service -n microservices-demo -f"
echo ""
echo "   Просмотр метрик подов:"
echo "   kubectl top pods -n microservices-demo"
echo ""
echo "   Просмотр нагрузки:"
echo "   kubectl get hpa -n microservices-demo 2>/dev/null || echo 'HPA не настроен'"
echo ""

echo "5. Примеры запросов для тестирования:"
echo "   # Создать пользователя:"
echo "   curl -X POST http://localhost:8080/users \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"name\":\"John Doe\",\"email\":\"john@example.com\"}'"
echo ""
echo "   # Получить метрики в Prometheus формате:"
echo "   curl http://localhost:8080/metrics"